sp

diff --git a/.github/workflows/dotnet-microservice.yml b/.github/workflows/dotnet-microservice.yml
--- a/.github/workflows/dotnet-microservice.yml
+++ b/.github/workflows/dotnet-microservice.yml
@@ -67,7 +67,7 @@ jobs:
       # Start 'Prepare Build Metadata and Environment'
       - name: Setup environmental variables
         run: |
-          echo Setting up env variables. Context: '$GITHUB_REF$'
+          echo "Setting up env variables. Context: $GITHUB_REF"
           echo "SOLUTION=$(node -p "require('./package.json').vsBuildSolution")" >> $GITHUB_ENV
           echo "APP_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV
           echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
@@ -83,22 +83,28 @@ jobs:
         run: |
           echo "APP_VERSION=${{ steps.version.outputs.app-version }}" >> $GITHUB_ENV
 
+      # - name: Check if Git Tag exists
+      #   id: git-tag-check
+      #   env:
+      #     APP_VERSION: ${{ steps.version.outputs.app-version }}
+      #   run: |
+      #     if git ls-remote --tags origin | grep -q "refs/tags/$APP_VERSION$"; then
+      #         echo "::error::Tag $APP_VERSION already exists."
+      #         exit 1
+      #     fi
+
+      #     TAG_EXISTS=$(git ls-remote --tags origin | grep -q "refs/tags/$PACKAGE_VERSION$")
+
+      #     if ! ${{ contains(github.ref_name, 'release/MW-') }} && ! TAG_EXISTS ; then
+      #         echo "::error::Tag $PACKAGE_VERSION was altered in a non-release branch."
+      #         exit 1
+      #     fi
+
       - name: Check if Git Tag exists
         id: git-tag-check
         env:
           APP_VERSION: ${{ steps.version.outputs.app-version }}
-        run: |
-          if git ls-remote --tags origin | grep -q "refs/tags/$APP_VERSION$"; then
-              echo "::error::Tag $APP_VERSION already exists."
-              exit 1
-          fi
-
-          TAG_EXISTS=$(git ls-remote --tags origin | grep -q "refs/tags/$PACKAGE_VERSION$")
-
-          if ! ${{ contains(github.ref_name, 'release/MW-') }} && ! TAG_EXISTS ; then
-              echo "::error::Tag $PACKAGE_VERSION was altered in a non-release branch."
-              exit 1
-          fi
+        uses: River-iGaming/actions/dotnet/tag-check@v3-dev
 
       # End 'Prepare Build Metadata and Environment'
 
