update

diff --git a/.github/workflows/frontend-build-and-publish-libs.yml b/.github/workflows/frontend-build-and-publish-libs.yml
--- a/.github/workflows/frontend-build-and-publish-libs.yml
+++ b/.github/workflows/frontend-build-and-publish-libs.yml
@@ -69,21 +69,21 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3.0.0
 
-      - name: Extract branch name
-        id: branch
-        run: |
-          EVENT=${{ github.event_name }}
-          if [ $EVENT == "pull_request" ]; then
-            BRANCH_NAME=${{github.head_ref}}
-            echo "::set-output name=name::${BRANCH_NAME}"
-          else
-            echo "::set-output name=name::${GITHUB_REF_NAME}"
-          fi
+      # - name: Extract branch name
+      #   id: branch
+      #   run: |
+      #     EVENT=${{ github.event_name }}
+      #     if [ $EVENT == "pull_request" ]; then
+      #       BRANCH_NAME=${{github.head_ref}}
+      #       echo "::set-output name=name::${BRANCH_NAME}"
+      #     else
+      #       echo "::set-output name=name::${GITHUB_REF_NAME}"
+      #     fi
 
-      - name: Install npm
-        run: npm ci
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
+      # - name: Install npm
+      #   run: npm ci
+      #   env:
+      #     NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
 
       # - name: Build
       #   run: npm run build
@@ -95,18 +95,18 @@ jobs:
       #   if: inputs.has-storybook
       #   run: npm run build:storybook
 
-      - name: Check if branch is publishable
-        id: check-branch
-        run: |
-          BRANCH_NAME=${{steps.branch.outputs.name}}
-          echo "::notice ::Branch name: $BRANCH_NAME"
+      # - name: Check if branch is publishable
+      #   id: check-branch
+      #   run: |
+      #     BRANCH_NAME=${{steps.branch.outputs.name}}
+      #     echo "::notice ::Branch name: $BRANCH_NAME"
 
-          if ! ([ $BRANCH_NAME = "master" ] || [ $BRANCH_NAME = "vnext" ] || [[ "$BRANCH_NAME" =~ ^([0-9].*)\.x$ ]]); then
-            echo "::set-output name=publishable::false"
-            echo "::notice ::Non-publishable branch."
-          else 
-            echo "::set-output name=publishable::true"
-          fi
+      #     if ! ([ $BRANCH_NAME = "master" ] || [ $BRANCH_NAME = "vnext" ] || [[ "$BRANCH_NAME" =~ ^([0-9].*)\.x$ ]]); then
+      #       echo "::set-output name=publishable::false"
+      #       echo "::notice ::Non-publishable branch."
+      #     else 
+      #       echo "::set-output name=publishable::true"
+      #     fi
 
       - name: Check if commit is publishable
         id: commit
@@ -120,87 +120,87 @@ jobs:
             echo "::set-output name=publishable::true"
           fi
 
-      - name: Fetch tag from lerna
-        id: lerna
-        if: ${{ steps.commit.outputs.publishable == 'true' }}
-        run: |
-          TAG=$(node -p "require('./lerna.json').version")
-          echo "::set-output name=tag::${TAG}"
+      # - name: Fetch tag from lerna
+      #   id: lerna
+      #   if: ${{ steps.commit.outputs.publishable == 'true' }}
+      #   run: |
+      #     TAG=$(node -p "require('./lerna.json').version")
+      #     echo "::set-output name=tag::${TAG}"
 
-      - name: Check if tag exists
-        uses: mukunku/tag-exists-action@v1.0.0
-        id: tag
-        with: 
-          tag: ${{ steps.lerna.outputs.tag }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.github-token }}
+      # - name: Check if tag exists
+      #   uses: mukunku/tag-exists-action@v1.0.0
+      #   id: tag
+      #   with: 
+      #     tag: ${{ steps.lerna.outputs.tag }}
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.github-token }}
 
-      - name: Inform if tag exists
-        if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.exists == 'true' }}
-        run: |
-          echo "::error ::Tag already exists. Please make sure you bump version!"
-          exit 1
+      # - name: Inform if tag exists
+      #   if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.exists == 'true' }}
+      #   run: |
+      #     echo "::error ::Tag already exists. Please make sure you bump version!"
+      #     exit 1
 
-      - name: Configure AWS credentials
-        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.aws-access-key-id }}
-          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
-          aws-region: ${{ inputs.aws-region }}
+      # - name: Configure AWS credentials
+      #   if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
+      #   uses: aws-actions/configure-aws-credentials@v1
+      #   with:
+      #     aws-access-key-id: ${{ secrets.aws-access-key-id }}
+      #     aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
+      #     aws-region: ${{ inputs.aws-region }}
 
-      - name: Login to Amazon ECR
-        id: login-ecr
-        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
-        uses: aws-actions/amazon-ecr-login@v1
+      # - name: Login to Amazon ECR
+      #   id: login-ecr
+      #   if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
+      #   uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Publish storybook
-        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
-        env:
-          ECR_HOST: ${{ steps.login-ecr.outputs.registry }} 
-        run: |
-          BRANCH_NAME=${{steps.branch.outputs.name}}
-          TAG=$(node -p "require('./storybook/package.json').version")
-          if [ "$CIRCLE_BRANCH" = "develop" ]
-          then
-            TAG=$TAG-dev-$GITHUB_RUN_ID
-          elif [[ "$BRANCH_NAME" =~ ^feature\/(.*)$ ]]
-          then
-            TAG=$TAG-demo-${BASH_REMATCH[1]}-$GITHUB_RUN_ID
-          fi
+      # - name: Publish storybook
+      #   if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
+      #   env:
+      #     ECR_HOST: ${{ steps.login-ecr.outputs.registry }} 
+      #   run: |
+      #     BRANCH_NAME=${{steps.branch.outputs.name}}
+      #     TAG=$(node -p "require('./storybook/package.json').version")
+      #     if [ "$CIRCLE_BRANCH" = "develop" ]
+      #     then
+      #       TAG=$TAG-dev-$GITHUB_RUN_ID
+      #     elif [[ "$BRANCH_NAME" =~ ^feature\/(.*)$ ]]
+      #     then
+      #       TAG=$TAG-demo-${BASH_REMATCH[1]}-$GITHUB_RUN_ID
+      #     fi
 
-          [[ $ECR_HOST =~ ^([0-9]*) ]] && REGISTRY=${BASH_REMATCH[1]}
+      #     [[ $ECR_HOST =~ ^([0-9]*) ]] && REGISTRY=${BASH_REMATCH[1]}
 
-          if aws ecr describe-images --repository-name=odin.ngx-storybook --registry-id $REGISTRY --image-ids=imageTag=$TAG > /dev/null 2>&1; then
-            echo "::notice ::$TAG already exists on remote... skipping..."
-            exit 0
-          fi
+      #     if aws ecr describe-images --repository-name=odin.ngx-storybook --registry-id $REGISTRY --image-ids=imageTag=$TAG > /dev/null 2>&1; then
+      #       echo "::notice ::$TAG already exists on remote... skipping..."
+      #       exit 0
+      #     fi
 
-          TAG=$TAG docker-compose build
-          TAG=$TAG docker-compose push
+      #     TAG=$TAG docker-compose build
+      #     TAG=$TAG docker-compose push
 
-      - name: Logout of Amazon ECR
-        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
-        run: docker logout ${{ steps.login-ecr.outputs.registry }}
+      # - name: Logout of Amazon ECR
+      #   if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
+      #   run: docker logout ${{ steps.login-ecr.outputs.registry }}
 
-      - name: Deploy
-        if: ${{ steps.check-branch.outputs.publishable == 'true' && steps.commit.outputs.publishable == 'true' }}
-        run: |
-          echo "git tag"
-          PACKAGE_VERSION=$(node -p "require('./lerna.json').version")
-          git tag $PACKAGE_VERSION
-          git push origin $PACKAGE_VERSION
-          npm run publish:rel
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
+      # - name: Deploy
+      #   if: ${{ steps.check-branch.outputs.publishable == 'true' && steps.commit.outputs.publishable == 'true' }}
+      #   run: |
+      #     echo "git tag"
+      #     PACKAGE_VERSION=$(node -p "require('./lerna.json').version")
+      #     git tag $PACKAGE_VERSION
+      #     git push origin $PACKAGE_VERSION
+      #     npm run publish:rel
+      #   env:
+      #     NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
 
-      - name: Store tests artifact
-        uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: ${{ inputs.junit-report-name }}
-          path: ${{ inputs.junit-report-path }}
-          retention-days: 2
+      # - name: Store tests artifact
+      #   uses: actions/upload-artifact@v3
+      #   if: failure()
+      #   with:
+      #     name: ${{ inputs.junit-report-name }}
+      #     path: ${{ inputs.junit-report-path }}
+      #     retention-days: 2
 
       - name: Store npm artifact
         uses: actions/upload-artifact@v3
