update

diff --git a/.github/workflows/frontend-build-and-publish-libs.yml b/.github/workflows/frontend-build-and-publish-libs.yml
--- a/.github/workflows/frontend-build-and-publish-libs.yml
+++ b/.github/workflows/frontend-build-and-publish-libs.yml
@@ -84,20 +84,20 @@ jobs:
             echo ::set-output name=commit-message::$(git log --format=%B -n 1 HEAD)
           fi
 
-      # - name: Install npm
-      #   run: npm ci
-      #   env:
-      #     NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
+      - name: Install npm
+        run: npm ci
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
 
-      # - name: Build
-      #   run: npm run build
+      - name: Build
+        run: npm run build
 
-      # - name: Test
-      #   run: npm run test -- --browsers=ChromeHeadlessCI --no-watch --no-progress
+      - name: Test
+        run: npm run test -- --browsers=ChromeHeadlessCI --no-watch --no-progress
 
-      # - name: Build storybook
-      #   if: inputs.has-storybook
-      #   run: npm run build:storybook
+      - name: Build storybook
+        if: inputs.has-storybook
+        run: npm run build:storybook
 
       - name: Check if branch is publishable
         id: check-branch
@@ -113,15 +113,13 @@ jobs:
             echo "::set-output name=publishable::true"
           fi
 
-     
-
       - name: Check if commit is publishable
         id: commit
         env:
           COMMIT_MESSAGE: ${{ steps.git.outputs.commit-message}}
         run: |
           echo "::notice ::Commit message: $COMMIT_MESSAGE"
-          
+
           if [[ "$COMMIT_MESSAGE" =~ ^(style|test|docs) ]]; then
             echo "::set-output name=publishable::false"
             echo "::notice ::This update doesn't need to be published."
@@ -129,87 +127,87 @@ jobs:
             echo "::set-output name=publishable::true"
           fi
 
-      # - name: Fetch tag from lerna
-      #   id: lerna
-      #   if: ${{ steps.commit.outputs.publishable == 'true' }}
-      #   run: |
-      #     TAG=$(node -p "require('./lerna.json').version")
-      #     echo "::set-output name=tag::${TAG}"
+      - name: Fetch tag from lerna
+        id: lerna
+        if: ${{ steps.commit.outputs.publishable == 'true' }}
+        run: |
+          TAG=$(node -p "require('./lerna.json').version")
+          echo "::set-output name=tag::${TAG}"
 
-      # - name: Check if tag exists
-      #   uses: mukunku/tag-exists-action@v1.0.0
-      #   id: tag
-      #   with: 
-      #     tag: ${{ steps.lerna.outputs.tag }}
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.github-token }}
+      - name: Check if tag exists
+        uses: mukunku/tag-exists-action@v1.0.0
+        id: tag
+        with: 
+          tag: ${{ steps.lerna.outputs.tag }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.github-token }}
 
-      # - name: Inform if tag exists
-      #   if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.exists == 'true' }}
-      #   run: |
-      #     echo "::error ::Tag already exists. Please make sure you bump version!"
-      #     exit 1
+      - name: Inform if tag exists
+        if: ${{ steps.commit.outputs.publishable == 'true' && steps.tag.outputs.exists == 'true' }}
+        run: |
+          echo "::error ::Tag already exists. Please make sure you bump version!"
+          exit 1
 
-      # - name: Configure AWS credentials
-      #   if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
-      #   uses: aws-actions/configure-aws-credentials@v1
-      #   with:
-      #     aws-access-key-id: ${{ secrets.aws-access-key-id }}
-      #     aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
-      #     aws-region: ${{ inputs.aws-region }}
+      - name: Configure AWS credentials
+        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.aws-access-key-id }}
+          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
+          aws-region: ${{ inputs.aws-region }}
 
-      # - name: Login to Amazon ECR
-      #   id: login-ecr
-      #   if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
-      #   uses: aws-actions/amazon-ecr-login@v1
+      - name: Login to Amazon ECR
+        id: login-ecr
+        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
+        uses: aws-actions/amazon-ecr-login@v1
 
-      # - name: Publish storybook
-      #   if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
-      #   env:
-      #     ECR_HOST: ${{ steps.login-ecr.outputs.registry }} 
-      #   run: |
-      #     BRANCH_NAME=${{steps.branch.outputs.name}}
-      #     TAG=$(node -p "require('./storybook/package.json').version")
-      #     if [ "$CIRCLE_BRANCH" = "develop" ]
-      #     then
-      #       TAG=$TAG-dev-$GITHUB_RUN_ID
-      #     elif [[ "$BRANCH_NAME" =~ ^feature\/(.*)$ ]]
-      #     then
-      #       TAG=$TAG-demo-${BASH_REMATCH[1]}-$GITHUB_RUN_ID
-      #     fi
+      - name: Publish storybook
+        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
+        env:
+          ECR_HOST: ${{ steps.login-ecr.outputs.registry }} 
+        run: |
+          BRANCH_NAME=${{steps.branch.outputs.name}}
+          TAG=$(node -p "require('./storybook/package.json').version")
+          if [ "$CIRCLE_BRANCH" = "develop" ]
+          then
+            TAG=$TAG-dev-$GITHUB_RUN_ID
+          elif [[ "$BRANCH_NAME" =~ ^feature\/(.*)$ ]]
+          then
+            TAG=$TAG-demo-${BASH_REMATCH[1]}-$GITHUB_RUN_ID
+          fi
 
-      #     [[ $ECR_HOST =~ ^([0-9]*) ]] && REGISTRY=${BASH_REMATCH[1]}
+          [[ $ECR_HOST =~ ^([0-9]*) ]] && REGISTRY=${BASH_REMATCH[1]}
 
-      #     if aws ecr describe-images --repository-name=odin.ngx-storybook --registry-id $REGISTRY --image-ids=imageTag=$TAG > /dev/null 2>&1; then
-      #       echo "::notice ::$TAG already exists on remote... skipping..."
-      #       exit 0
-      #     fi
+          if aws ecr describe-images --repository-name=odin.ngx-storybook --registry-id $REGISTRY --image-ids=imageTag=$TAG > /dev/null 2>&1; then
+            echo "::notice ::$TAG already exists on remote... skipping..."
+            exit 0
+          fi
 
-      #     TAG=$TAG docker-compose build
-      #     TAG=$TAG docker-compose push
+          TAG=$TAG docker-compose build
+          TAG=$TAG docker-compose push
 
-      # - name: Logout of Amazon ECR
-      #   if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
-      #   run: docker logout ${{ steps.login-ecr.outputs.registry }}
+      - name: Logout of Amazon ECR
+        if: ${{ inputs.has-storybook && steps.commit.outputs.publishable == 'true' }}
+        run: docker logout ${{ steps.login-ecr.outputs.registry }}
 
-      # - name: Deploy
-      #   if: ${{ steps.check-branch.outputs.publishable == 'true' && steps.commit.outputs.publishable == 'true' }}
-      #   run: |
-      #     echo "git tag"
-      #     PACKAGE_VERSION=$(node -p "require('./lerna.json').version")
-      #     git tag $PACKAGE_VERSION
-      #     git push origin $PACKAGE_VERSION
-      #     npm run publish:rel
-      #   env:
-      #     NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
+      - name: Deploy
+        if: ${{ steps.check-branch.outputs.publishable == 'true' && steps.commit.outputs.publishable == 'true' }}
+        run: |
+          echo "git tag"
+          PACKAGE_VERSION=$(node -p "require('./lerna.json').version")
+          git tag $PACKAGE_VERSION
+          git push origin $PACKAGE_VERSION
+          npm run publish:rel
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
 
-      # - name: Store tests artifact
-      #   uses: actions/upload-artifact@v3
-      #   if: failure()
-      #   with:
-      #     name: ${{ inputs.junit-report-name }}
-      #     path: ${{ inputs.junit-report-path }}
-      #     retention-days: 2
+      - name: Store tests artifact
+        uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: ${{ inputs.junit-report-name }}
+          path: ${{ inputs.junit-report-path }}
+          retention-days: 2
 
       - name: Store npm artifact
         uses: actions/upload-artifact@v3
