fix(frontend build and publish apps): downmerge fail if conflicts

diff --git a/.github/workflows/frontend-build-and-publish-apps.yml b/.github/workflows/frontend-build-and-publish-apps.yml
--- a/.github/workflows/frontend-build-and-publish-apps.yml
+++ b/.github/workflows/frontend-build-and-publish-apps.yml
@@ -330,10 +330,11 @@ jobs:
           else
             if git merge HEAD
             then
-              echo "::notice ::"Nothing to merge"
+              echo "::notice ::Nothing to merge"
             else
-              echo "::warning ::"Failed to downmerge. Conflicts between master and develop."
+              echo "::warning ::Failed to downmerge. Conflicts between master and develop."
               git merge --abort
+              exit 1
             fi
           fi
 
