feat(node libs): npm token support

diff --git a/.github/workflows/node-libs.yml b/.github/workflows/node-libs.yml
--- a/.github/workflows/node-libs.yml
+++ b/.github/workflows/node-libs.yml
@@ -58,10 +58,12 @@ on:
         default: false
         required: false
     secrets:
+      npm-token:
+        required: false
       nexus-username:
-        required: true
+        required: false
       nexus-password:
-        required: true
+        required: false
       aws-access-key-id:
         required: true
       aws-secret-access-key:
@@ -93,7 +95,14 @@ jobs:
       - name: NPM TOKEN
         id: npm_token
         run: |
-          NODE_AUTH_TOKEN=$(echo -n "${{ secrets.nexus-username }}:${{ secrets.nexus-password }}" | openssl base64 -e)
+          if [[ "${{ secrets.npm-token }}" ]]; then
+            NODE_AUTH_TOKEN=$(echo -n "${{ secrets.npm-token }}")
+          elif [[ "${{ secrets.nexus-username }}" && "${{ secrets.nexus-password }}" ]]; then
+            NODE_AUTH_TOKEN=$(echo -n "${{ secrets.nexus-username }}:${{ secrets.nexus-password }}" | openssl base64 -e)
+          else
+            echo "Error: Neither npm-token nor nexus-username/nexus-password provided." >&2
+            exit 1
+          fi
           echo "token=${NODE_AUTH_TOKEN}" >> "$GITHUB_OUTPUT"
 
       - name: Setup Node
