feat(config version): check config package version with branch name

diff --git a/.github/workflows/vor-check-config.yml b/.github/workflows/vor-check-config.yml
--- a/.github/workflows/vor-check-config.yml
+++ b/.github/workflows/vor-check-config.yml
@@ -26,6 +26,14 @@ jobs:
         run: |
           PACKAGE_VERSION=$(node -p "require('./package.json').version")
           echo "::set-output name=package-version::$PACKAGE_VERSION"
+      - name: Check branch name and package version should match
+        run: |
+        if [[ "${BRANCH_VERSION_PREFIX}" == "${PACKAGE_VERSION%%.*}" ]]; then
+          echo "Branch name matches package version prefix"
+        else
+          echo "Branch name does not match package version prefix"
+          echo "::error::Branch name [$BRANCH_VERSION_PREFIX] does not match package version [$PACKAGE_VERSION] prefix"
+          exit 1
       - name: Check if tag exists
         uses: mukunku/tag-exists-action@v1.0.0
         id: tag
